# Setup
title: Kuquert
tagline: Hobbies and learing expierences
description: "Randon thinkery box for diverse ideas"
url: https://kuquert.github.io
baseurl: /
theme: minima

# Author info
twitter_username: kuquert
github_username:  kuquert

# Plugins config
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll-admin

paginate: 5

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

