# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Kuquert
tagline:          Hobbies and learing expierences
description:      "Randon thinkery box for diverse ideas"
url:              https://kuquert.github.io
baseurl:          /

author:
  name:           Marcus Kuquert
  bio:            "Mobile software engineer w/4+ years of experience. Worked at IT companies in fields including IOT, FinTech and Health. Using languages such as Objective-C, Swift and Kotlin. Worked with R&D at Microgravity Center at PUCRS, including areas like circuit boards design and 3d printing. Participant of Apple Developer Academy program, including projects using Apple`s ResearchKit for mobile health research."
  twitter:        https://twitter.com/kuquert
  github:         https://github.com/kuquert


paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/karloespiritu/blackdoc

theme: jekyll-theme-midnight